# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8642e30d593b9d73be7772d7147baeefac7c2caaac1ab6f44c78970c12df5a88df5c4f33c21254370daea349cf6f08f52262a575263612ae1afe40228215ac45

test:
  secret_key_base: 8b32afce45da6cf2af589dfa3fc6b3520ec53306f710c2649daf561c4b2d9fd0409f6d57fa42255a3458807c608d5ca12854316c6769f1a3f45807c8ca6c7664

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
